project:
  type: website

website:
  title: "Spotify Dashboard"
  favicon: images/logo.png
  page-navigation: true
  site-url: https://mariojreyes.github.io/spotify-dashboard/
  repo-url: https://github.com/MariojReyes/spotify-dashboard
  repo-actions: [edit, source, issue]
  sidebar:
    title: "Billboard Hot 100"
    style: "docked"
    search: true
    collapse-level: 1
    logo: images/logo.png
    contents: 
      - href: dashboard.qmd
        text: Dashboard
      - href: about.qmd
        text: About Me

format:
  html:
    theme: [cosmo, custom.scss]
    highlight-style: atom-one-dark
    toc: true
    grid:
      sidebar-width: 150px
